### ISSUE TITLE
conda packaging for Python 3.10

### ISSUE THREAD

**Issue by mrakitin** [NSLS-II-CSX/csxtools#81]
https://github.com/conda-forge/csxtools-feedstock/pull/3 failed with a missing import. Need to resolve it on the package level and release a new version with the fix.

```py
import: 'csxtools'
/home/conda/feedstock_root/build_artifacts/csxtools_1642620788862/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.10/site-packages/pims/image_reader.py:26: RuntimeWarning: PIMS image_reader.py could not find scikit-image. Falling back to matplotlib's imread(), which uses floats instead of integers. This may break your scripts. 
(To ignore this warning, include the line "warnings.simplefilter("ignore", RuntimeWarning)" in your script.)
  warnings.warn(RuntimeWarning(ski_preferred))
Traceback (most recent call last):
  File "/home/conda/feedstock_root/build_artifacts/csxtools_1642620788862/test_tmp/run_test.py", line 2, in <module>
    import csxtools
  File "/home/conda/feedstock_root/build_artifacts/csxtools_1642620788862/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.10/site-packages/csxtools/__init__.py", line 3, in <module>
    from .utils import (get_fastccd_images, get_fastccd_timestamps)  # noqa F401
  File "/home/conda/feedstock_root/build_artifacts/csxtools_1642620788862/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.10/site-packages/csxtools/utils.py", line 3, in <module>
    from pims import pipeline
  File "/home/conda/feedstock_root/build_artifacts/csxtools_1642620788862/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.10/site-packages/pims/__init__.py", line 1, in <module>
    from pims.api import *
  File "/home/conda/feedstock_root/build_artifacts/csxtools_1642620788862/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.10/site-packages/pims/api.py", line 19, in <module>
    from .cine import Cine  # noqa
  File "/home/conda/feedstock_root/build_artifacts/csxtools_1642620788862/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.10/site-packages/pims/cine.py", line 29, in <module>
    from collections import Iterable
ImportError: cannot import name 'Iterable' from 'collections' (/home/conda/feedstock_root/build_artifacts/csxtools_1642620788862/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.10/collections/__init__.py)
Tests failed for csxtools-0.1.16-py310hb5077e9_1.tar.bz2 - moving package to /home/conda/feedstock_root/build_artifacts/broken
```

**Comment by ambarb** [comment]
slack channel note:
`from collections.abc import Iterable`
